# Generated by Django 5.1.3 on 2026-04-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locker_number', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance'), ('deactivated', 'Deactivated')], default='available', max_length=20)),
                ('size', models.CharField(default='medium', help_text='Small, Medium, Large', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['locker_number'],
                'indexes': [models.Index(fields=['status'], name='lockers_loc_status_e1ed38_idx'), models.Index(fields=['locker_number'], name='lockers_loc_locker__ab9169_idx')],
            },
        ),
    ]
